server:
  port: 3001
  rapidapikey: '646c91d8fdmshf140e18f8eec60ep193bfejsna584cd4dfee2'

db:
  host: "localhost"
  type: "mongodb"
  port: 5435
  database: "thing_api"
  synchronize: true
  username: "thing_api"
  password: "Codelight123"
  mongourl: "mongodb://thing_api:Codelight123@cluster0-shard-00-00.nxuuk.mongodb.net:27017,cluster0-shard-00-01.nxuuk.mongodb.net:27017,cluster0-shard-00-02.nxuuk.mongodb.net:27017/thing_api?ssl=true&replicaSet=atlas-lg2imm-shard-0&authSource=admin&retryWrites=true&w=majority"


jwt:
  expiresIn: 3600
